In [5]:
import pandas as pd

file = pd.read_csv("C:\\Users\\Aditi\\Downloads\\iris.csv")

1. Import Iris Dataset and visualize the first 20 rows
2. Visualize columns names and extract statistical description 
3. Filter the rows with sepal.length > 7
4. Visualize rows from 25 to 35 using "iloc"
5. Verify if there are Nans
6. Create a new column named "petal.attributes" summing "petal.length" and "petal.width"
7. Multiply each element of this new column for 10

In [91]:
print(file.head(20))

    sepal.length  sepal.width  petal.length  petal.width variety  \
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa

    petal.attributes
0              160.0
1              160.0
2              150.0
3              170.0
4              160.0
5              210.0
6              170.0
7              170.0
8              160.0
9              160.0
10             170.0
11             180.0
12             150.0
13             120.0
14             140.0
15             190.0
16             170.0
17             170.0
18             200.0
19             180.0

In [92]:
file.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'petal.attributes'],
      dtype='object')

In [8]:
file.describe(include="all")

        sepal.length  sepal.width  petal.length  petal.width variety
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  Setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [95]:
#file.loc[file['sepal.length']>7]
file[file['sepal.length']>7]

,sepal.length,sepal.width,petal.length,petal.width,variety,petal.attributes
102,7.1,3.0,5.9,2.1,Virginica,800.0
105,7.6,3.0,6.6,2.1,Virginica,870.0
107,7.3,2.9,6.3,1.8,Virginica,810.0
109,7.2,3.6,6.1,2.5,Virginica,860.0
117,7.7,3.8,6.7,2.2,Virginica,890.0
118,7.7,2.6,6.9,2.3,Virginica,920.0
122,7.7,2.8,6.7,2.0,Virginica,870.0
125,7.2,3.2,6.0,1.8,Virginica,780.0
129,7.2,3.0,5.8,1.6,Virginica,740.0
130,7.4,2.8,6.1,1.9,Virginica,800.0
131,7.9,3.8,6.4,2.0,Virginica,840.0
135,7.7,3.0,6.1,2.3,Virginica,840.0

In [16]:
file.iloc[25:36]

    sepal.length  sepal.width  petal.length  petal.width variety
25           5.0          3.0           1.6          0.2  Setosa
26           5.0          3.4           1.6          0.4  Setosa
27           5.2          3.5           1.5          0.2  Setosa
28           5.2          3.4           1.4          0.2  Setosa
29           4.7          3.2           1.6          0.2  Setosa
30           4.8          3.1           1.6          0.2  Setosa
31           5.4          3.4           1.5          0.4  Setosa
32           5.2          4.1           1.5          0.1  Setosa
33           5.5          4.2           1.4          0.2  Setosa
34           4.9          3.1           1.5          0.2  Setosa
35           5.0          3.2           1.2          0.2  Setosa

In [109]:
#file.notna().sum()
#file.isnull().sum()
file.fillna(1)

,sepal.length,sepal.width,petal.length,petal.width,variety,petal.attributes
0,5.1,3.5,1.4,0.2,Setosa,1.6
1,4.9,3.0,1.4,0.2,Setosa,1.6
2,4.7,3.2,1.3,0.2,Setosa,1.5
3,4.6,3.1,1.5,0.2,Setosa,1.7
4,5.0,3.6,1.4,0.2,Setosa,1.6
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica,7.5
146,6.3,2.5,5.0,1.9,Virginica,6.9
147,6.5,3.0,5.2,2.0,Virginica,7.2
148,6.2,3.4,5.4,2.3,Virginica,7.7
149,5.9,3.0,5.1,1.8,Virginica,6.9

In [112]:
#file['petal.attributes'] = file['petal.length'] + file['petal.width']
#file.iloc[1:11]
file['petal.attributes'].insert(4)

AttributeError: 'Series' object has no attribute 'insert'

In [21]:
file['petal.attributes'] = file['petal.attributes']*10
file.iloc[1:11]

,sepal.length,sepal.width,petal.length,petal.width,variety,petal.attributes
1,4.9,3.0,1.4,0.2,Setosa,160.0
2,4.7,3.2,1.3,0.2,Setosa,150.0
3,4.6,3.1,1.5,0.2,Setosa,170.0
4,5.0,3.6,1.4,0.2,Setosa,160.0
5,5.4,3.9,1.7,0.4,Setosa,210.0
6,4.6,3.4,1.4,0.3,Setosa,170.0
7,5.0,3.4,1.5,0.2,Setosa,170.0
8,4.4,2.9,1.4,0.2,Setosa,160.0
9,4.9,3.1,1.5,0.1,Setosa,160.0
10,5.4,3.7,1.5,0.2,Setosa,170.0

numpy

In [23]:
import numpy as np

- Given the following arrays:

   v = np.array([1,2,4,3,5])
   a = np.array([1,2],[3,4])
   b = np.array([5,6],[7,8])
   
   1. Visualize the size and the shape of v and a
   2. Compute maximum, minimum, mean and standard deviation of v
   3. Compute the transpose of a
   4. Sort the elements of v
   5. Apply the mathematical operations + , - , * , / and ** between a and b
   6. Compute the dot product between a and b
   7. Create an array that contains number from 0 to 9
   8. Create a 2x2 matrix of zeroes, a 2x2 matrix of ones and a 2x2 identity matrix
   9. Extract elements of v that are >2
   10. Extract diagonal elements of a
   11. Create a 3x3 matrix full of 5 with 7 in the diagonal

In [30]:
v = np.array([1,2,4,3,5])
print(v)

[1 2 4 3 5]

In [34]:
a = np.array([[1,2],[3,4]])

In [35]:
b = np.array([[5,6],[7,8]])

In [38]:

print(np.size(v))
print(np.shape(v))


print(np.size(a))
print(np.shape(a))

5
(5,)
4
(2, 2)

In [80]:
print(np.max(v),"--",
np.min(v),"--",
np.std(v))

5 -- 1 -- 1.4142135623730951

In [42]:
print(np.transpose(a))

[[1 3]
 [2 4]]

In [43]:
print(np.sort(v))

[1 2 3 4 5]

In [45]:
print(a+b,"--",a-b,"--",a*b,"--",a/b,"--",a**b)

[[ 6  8]
 [10 12]] -- [[-4 -4]
 [-4 -4]] -- [[ 5 12]
 [21 32]] -- [[0.2        0.33333333]
 [0.42857143 0.5       ]] -- [[    1    64]
 [ 2187 65536]]

In [58]:
print(a.dot(b))

[[19 22]
 [43 50]]

In [83]:
m = np.array([0,1,2,3,4,5,6,7,8,9])
m = np.arange(10)
print(m)

[0 1 2 3 4 5 6 7 8 9]

In [48]:
p = np.zeros(2)
q = np.ones(2)
r = np.eye(2)
print(p,q,r)

[0. 0.] [1. 1.] [[1. 0.]
 [0. 1.]]

In [85]:
np.extract(v,v>2)
v[v>2]

array([4, 3, 5])

In [60]:
print(a.diagonal())

[1 4]

In [79]:
s =np.full((3,3),5)
s[np.diag_indices(3)] =7
print(s)

[[7 5 5]
 [5 7 5]
 [5 5 7]]

In [88]:
s =np.full((3,3),5)
s_eye = np.eye(3)

s[s_eye == 1]=7
print(s)

[[7 5 5]
 [5 7 5]
 [5 5 7]]